name: "Upload"

on:
  workflow_call:
    inputs:
        job:
            required: true
            type: string
        jobs:
            required: true
            type: string
                

jobs:
    build1:
        name: Build the CSV
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: write
            security-events: write
        
        steps:
            - uses: actions/checkout@v2
              with:
                persist-credentials: false 
                fetch-depth: 0
            - run: |
                pip3 install -r requirements.txt
                python3 main.py --job ${{ inputs.job }} --jobs ${{ inputs.jobs }} --remove-header -o csv-dump-${{inputs.job}}.csv
            - uses: actions/upload-artifact@v3
              with:
                name: csv-build-${{inputs.job}}
                path: csv-dump-${{inputs.job}}.csv

    